<a href="https://colab.research.google.com/github/kvnptl/pytorch-practice/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learn PyTorch by Coding 

[1] My Github repo: https://github.com/kvnptl/pytorch-practice

[2] Reference Video: https://www.youtube.com/watch?v=Z_ikDlimN6A&t=83869s 

[3] Reference Book: https://www.learnpytorch.io/00_pytorch_fundamentals/#creating-tensors 



In [1]:
import torch
import numpy as np
print(torch.__version__)

1.13.0+cu116


### Introduction to tensor

Document - `torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html

# Variable naming convention

- Keep scalar and vector in Lower case
- Keep MATRIX and TENSOR in Upper case

#### Scalar

In [2]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

#### Vector

In [5]:
# vector
vector =  torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim # count number of [] brackets

1

In [7]:
vector.shape

torch.Size([2])

#### MATRIX

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0] # 0th row

tensor([7, 8])

#### TENSOR

In [12]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR[0][1]

tensor([4, 5, 6])

In [17]:
TENSOR[0][1][0]

tensor(4)

#### RANDOM TENSORS

In [18]:
## RANDOM TENSORS

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.8497, 0.5455, 0.9269, 0.3293],
        [0.1719, 0.6214, 0.3819, 0.5367],
        [0.4748, 0.8052, 0.4393, 0.9754]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor_2 = torch.rand(5, 3, 4)
random_tensor_2

tensor([[[0.5949, 0.5744, 0.6060, 0.0903],
         [0.1511, 0.2434, 0.8409, 0.6549],
         [0.8044, 0.6348, 0.4626, 0.2702]],

        [[0.0456, 0.1259, 0.1213, 0.8907],
         [0.8650, 0.4682, 0.5168, 0.1525],
         [0.6691, 0.6600, 0.0529, 0.6317]],

        [[0.7260, 0.9699, 0.4941, 0.6879],
         [0.7578, 0.7434, 0.1537, 0.0315],
         [0.3124, 0.8029, 0.3544, 0.6380]],

        [[0.8501, 0.6543, 0.9748, 0.4702],
         [0.4071, 0.4435, 0.0863, 0.8622],
         [0.5596, 0.6697, 0.8845, 0.4101]],

        [[0.4029, 0.7826, 0.4381, 0.4307],
         [0.8822, 0.4334, 0.6963, 0.9814],
         [0.6040, 0.0761, 0.9836, 0.5390]]])

In [21]:
random_tensor_2.ndim

3

In [22]:
random_image_size_tensor = torch.rand(size=(3, 224,224)) # channel, height, width
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

In [23]:
random_tensor_3 = torch.rand(1,1,3,3)
random_tensor_3.ndim, random_tensor_3.shape

(4, torch.Size([1, 1, 3, 3]))

In [24]:
# zeros and ones

zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))

In [25]:
ones.dtype # default is float 32

torch.float32

### Creating a range od tensors and tesnors-like

In [26]:
a_range = torch.arange(start=0, end=1000, step=50)
a_range.ndim, a_range.shape

(1, torch.Size([20]))

In [27]:
# creating tensors like 
# create a new tensor same as input tensor size

alike = torch.zeros_like(input=a_range)
alike

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### TENSOR datatypes

- float32 = single precision
- float16 = half precision

In [28]:
float_32_tensor = torch.tensor([3.,6.,9.], dtype=None, device=None, requires_grad=False)
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = torch.tensor([1,2,3], dtype=torch.float16) # or dtype=torch.half
float_16_tensor.dtype

torch.float16

In [30]:
tensor_mul = float_16_tensor*float_32_tensor
tensor_mul.dtype

torch.float32

### Getting information from tensors

In [31]:
some_tensor = torch.rand(3,5, dtype=torch.float64)
some_tensor

tensor([[0.9236, 0.6298, 0.3755, 0.7851, 0.3198],
        [0.0689, 0.7766, 0.2730, 0.4082, 0.0565],
        [0.6506, 0.0560, 0.1545, 0.4517, 0.0851]], dtype=torch.float64)

In [32]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shpae of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.9236, 0.6298, 0.3755, 0.7851, 0.3198],
        [0.0689, 0.7766, 0.2730, 0.4082, 0.0565],
        [0.6506, 0.0560, 0.1545, 0.4517, 0.0851]], dtype=torch.float64)
Datatype of tensor: torch.float64
Shpae of tensor: torch.Size([3, 5])
Device of tensor: cpu


### Manipulating tensors

These operations are often a wonderful dance between:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [33]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
%%time
tensor * 10

CPU times: user 1.21 ms, sys: 41 µs, total: 1.25 ms
Wall time: 1.18 ms


tensor([10, 20, 30])

In [44]:
%%time
torch.mul(tensor, 10)

CPU times: user 482 µs, sys: 0 ns, total: 482 µs
Wall time: 490 µs


tensor([10, 20, 30])

In [35]:
tensor - 5

tensor([-4, -3, -2])

In [36]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [37]:
torch.add(tensor, 3)

tensor([4, 5, 6])

In [38]:
# Matrix multiplication

tensor * tensor

tensor([1, 4, 9])

In [39]:
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
%%time
val = 0
for i in range(len(tensor)):
  val = tensor[i] * tensor[i]
print(val)

tensor(9)
CPU times: user 3.2 ms, sys: 0 ns, total: 3.2 ms
Wall time: 3.3 ms


In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 67 µs, sys: 18 µs, total: 85 µs
Wall time: 90.1 µs


tensor(14)

In [49]:
tensorA = torch.rand(size=(3,4))
tensorB = torch.rand(size=(4,3))
torch.matmul(tensorA, tensorB)

tensor([[0.4517, 0.4342, 0.4058],
        [0.2633, 0.3805, 0.4329],
        [0.5344, 0.5708, 0.4744]])

In [60]:
# find min, max, sum (tensor aggregation)

x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
torch.min(x)

tensor(0)

In [62]:
torch.max(x)

tensor(9)

In [63]:
torch.sum(x)

tensor(45)

In [65]:
torch.mean(x.type(torch.float32))

tensor(4.5000)