<a href="https://colab.research.google.com/github/kvnptl/pytorch-practice/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learn PyTorch by Coding 

[1] My Github repo: https://github.com/kvnptl/pytorch-practice

[2] Reference Video: https://www.youtube.com/watch?v=Z_ikDlimN6A&t=83869s 

[3] Reference Book: https://www.learnpytorch.io/00_pytorch_fundamentals/#creating-tensors 



In [1]:
import torch
import numpy as np
print(torch.__version__)

2.0.0+cu117


### Introduction to tensor

Document - `torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html

### Variable naming convention

- Keep scalar and vector in Lower case
- Keep MATRIX and TENSOR in Upper case

##### Scalar

In [2]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

##### Vector

In [14]:
# vector
vector =  torch.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.ndim # count number of [] brackets

1

In [16]:
# vector.item() # error
# so we can only get item from scalar
# to get item from vector, we need to specify index
vector[0].item(), vector[1].item()


(7, 7)

In [17]:
vector.shape

torch.Size([2])

##### MATRIX

In [22]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [23]:
MATRIX = torch.tensor(([7,8],
                       [9, 10])) # same as above
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [24]:
MATRIX.ndim

2

In [25]:
MATRIX.shape

torch.Size([2, 2])

In [26]:
MATRIX[0] # 0th row

tensor([7, 8])

##### TENSOR

In [27]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [28]:
TENSOR.ndim

3

In [29]:
TENSOR.shape

torch.Size([1, 3, 3])

In [30]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
TENSOR[0][1]

tensor([4, 5, 6])

In [32]:
TENSOR[0][1][0]

tensor(4)

### RANDOM TENSORS

In [33]:
## RANDOM TENSORS

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.9863, 0.9483, 0.8171, 0.1760],
        [0.3822, 0.0307, 0.1323, 0.8867],
        [0.6725, 0.9395, 0.3176, 0.3859]])

In [34]:
random_tensor.ndim

2

In [35]:
random_tensor_2 = torch.rand(5, 3, 4)
random_tensor_2

tensor([[[0.9073, 0.6677, 0.3093, 0.4383],
         [0.9294, 0.6889, 0.6757, 0.4167],
         [0.5890, 0.2259, 0.9658, 0.8059]],

        [[0.8557, 0.2646, 0.9752, 0.5649],
         [0.8750, 0.2200, 0.6182, 0.0931],
         [0.8606, 0.5282, 0.9698, 0.5010]],

        [[0.6896, 0.8936, 0.0136, 0.2178],
         [0.4003, 0.5598, 0.0052, 0.2609],
         [0.7864, 0.7604, 0.3285, 0.1761]],

        [[0.8932, 0.7973, 0.2822, 0.0992],
         [0.8275, 0.1611, 0.3301, 0.7086],
         [0.9297, 0.7612, 0.5483, 0.0597]],

        [[0.2569, 0.1476, 0.2845, 0.5797],
         [0.0949, 0.4013, 0.1127, 0.5339],
         [0.9367, 0.2362, 0.6341, 0.3928]]])

In [36]:
random_tensor_2.ndim

3

In [37]:
random_image_size_tensor = torch.rand(size=(3, 224,224)) # channel, height, width
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

In [38]:
random_tensor_3 = torch.rand(1,1,3,3)
random_tensor_3.ndim, random_tensor_3.shape

(4, torch.Size([1, 1, 3, 3]))

In [39]:
# zeros and ones

zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))

In [40]:
ones.dtype # default is float 32

torch.float32

### Creating a range of tensors and tesnors-like

In [41]:
a_range = torch.arange(start=0, end=1000, step=50)
a_range.ndim, a_range.shape

(1, torch.Size([20]))

In [43]:
# creating tensors like 
# create a new tensor same as input tensor size

alike = torch.zeros_like(input=a_range)
alike, alike.ndim, alike.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 1,
 torch.Size([20]))

### TENSOR datatypes

- float32 = single precision
- float16 = half precision

In [44]:
float_32_tensor = torch.tensor([3.,6.,9.], dtype=None, device=None, requires_grad=False)
float_32_tensor.dtype

torch.float32

In [45]:
float_16_tensor = torch.tensor([1,2,3], dtype=torch.float16) # or dtype=torch.half
float_16_tensor.dtype

torch.float16

In [46]:
tensor_mul = float_16_tensor*float_32_tensor # float 16 * float 32 = float 32
tensor_mul.dtype

torch.float32

### Getting information from tensors

In [47]:
some_tensor = torch.rand(3,5, dtype=torch.float64)
some_tensor

tensor([[0.2174, 0.3230, 0.7045, 0.2350, 0.9673],
        [0.6630, 0.3828, 0.4124, 0.8539, 0.4230],
        [0.9057, 0.6698, 0.3509, 0.8663, 0.5910]], dtype=torch.float64)

In [48]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shpae of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2174, 0.3230, 0.7045, 0.2350, 0.9673],
        [0.6630, 0.3828, 0.4124, 0.8539, 0.4230],
        [0.9057, 0.6698, 0.3509, 0.8663, 0.5910]], dtype=torch.float64)
Datatype of tensor: torch.float64
Shpae of tensor: torch.Size([3, 5])
Device of tensor: cpu


### Manipulating tensors

These operations are often a wonderful dance between:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [49]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [50]:
%%time
tensor * 10

CPU times: user 757 µs, sys: 311 µs, total: 1.07 ms
Wall time: 688 µs


tensor([10, 20, 30])

In [51]:
%%time
torch.mul(tensor, 10)

CPU times: user 1.02 ms, sys: 0 ns, total: 1.02 ms
Wall time: 901 µs


tensor([10, 20, 30])

In [52]:
tensor - 5

tensor([-4, -3, -2])

In [53]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [54]:
torch.add(tensor, 3)

tensor([4, 5, 6])

In [57]:
# Matrix multiplication

tensor * tensor # element wise multiplication

tensor([1, 4, 9])

In [59]:
torch.matmul(tensor, tensor) # matrix multiplication (dot product)

tensor(14)

In [68]:
%%time
# Withouth torch.matmul

val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i] 
print(val) 

tensor(14)
CPU times: user 1.03 ms, sys: 417 µs, total: 1.45 ms
Wall time: 906 µs


In [69]:
%%time
# With Pytorch matmul

torch.matmul(tensor, tensor) # faster

CPU times: user 320 µs, sys: 129 µs, total: 449 µs
Wall time: 317 µs


tensor(14)

In [70]:
tensorA = torch.rand(size=(3,4))
tensorB = torch.rand(size=(4,3))
torch.matmul(tensorA, tensorB)

tensor([[1.0657, 1.0778, 0.9774],
        [0.8047, 0.7566, 1.1038],
        [1.1126, 0.9135, 1.1990]])

In [72]:
# find min, max, sum (tensor aggregation)

x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
torch.min(x)

tensor(0)

In [74]:
torch.max(x)

tensor(9)

In [75]:
torch.sum(x)

tensor(45)

In [76]:
torch.mean(x.type(torch.float32))

tensor(4.5000)

### Reshaping, stacking, squeezing, and unsqueezing tensors

In [80]:
x = torch.arange(1., 10)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [81]:
# add extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [82]:
# add extra dimention

x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 2)

In [84]:
# change the view of tensor

z = x.view(1, 9) # same as reshape
z, z.shape

# NOTE: The difference between reshape and view is that view is only applicable to contiguous tensors (tensors in memory order) and it will return an error if the operation copies data.
# if you have a non-contiguous tensor, you need to call contiguous() before you can call view().
# Or better use reshape()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [85]:
# changing z changes x (because they share the same memory)

z[:, 0] = 5
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [86]:
# stacking at dimension 0 (row wise)

x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape, x_stacked.ndim


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]),
 2)

In [87]:
# stacking at dimension 1 (column wise)

x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x_stacked.shape, x_stacked.ndim

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]),
 2)

In [88]:
x_vstack = torch.vstack([x,x,x,x]) # same as stack with dim=0
x_vstack, x_vstack.shape, x_vstack.ndim

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]),
 2)

In [89]:
x_hstack = torch.hstack([x_reshaped, x_reshaped, x_reshaped, x_reshaped]) # same as stack with dim=1
x_hstack, x_hstack.shape, x_hstack.ndim

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]),
 2)

In [94]:
# squeeze removes all single dimensions from the tensor
# it does not matter where the single dimension is

x_reshaped.shape

torch.Size([1, 9])

In [95]:
x_squeexed = x_reshaped.squeeze()
x_squeexed, x_squeexed.shape, x_squeexed.ndim

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [97]:
# unsqueez adds a single dimension to a target tensor at a specific dimension

x_unsqueezed = x_squeexed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape, x_unsqueezed.ndim


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [98]:
x_unsqueezed = x_squeexed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape, x_unsqueezed.ndim

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 2)

In [99]:
# permute - rearranges the dimensions in a specific order
# REMEMBER: permute changes the same tensor in the memory location, be careful!!! 

x_original = torch.rand(size=(3, 224, 244))
print(f"x_original shape: {x_original.shape}")

x_permuted = x_original.permute(dims=(1,2,0))
print(f"x_permuted shape: {x_permuted.shape}")

x_original shape: torch.Size([3, 224, 244])
x_permuted shape: torch.Size([224, 244, 3])


In [100]:
x_og = torch.zeros(size=(1, 2, 4))
print(f"x_og and shape: {x_og}, {x_og.shape}")
x_perm = x_og.permute(dims=(2, 1, 0))
print(f"x_perm and shape: {x_perm}, {x_perm.shape}")
x_perm[0][0][0] = 5
x_og



x_og and shape: tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]), torch.Size([1, 2, 4])
x_perm and shape: tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]), torch.Size([4, 2, 1])


tensor([[[5., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### Indexing

In [101]:
## Indexing 

x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape, x.ndim


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [103]:
x[0], x[0].shape, x[0].ndim

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]),
 2)

In [104]:
x[0][0]

tensor([1, 2, 3])

In [105]:
x[0][0][0]

tensor(1)

In [106]:
x[0][0][0].item()

1

In [107]:
x[0][2][2].item()

9

In [110]:
x[:, 0]

tensor([[1, 2, 3]])

In [111]:
x[:,:,1]

tensor([[2, 5, 8]])

In [112]:
x[:, 1, 1]

tensor([5])

In [113]:
x[0, 0, :]

tensor([1, 2, 3])

In [114]:
x[:,:,2]

tensor([[3, 6, 9]])

### PyTorch tensors and NumPy

In [119]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array) # NOTE: NumPy default dtype is float64 while PyTorch default dtype is float32
array, hex(id(array)), array.dtype, tensor, hex(id(tensor)), tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 '0x7fcd85737330',
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 '0x7fcd8573b830',
 torch.float64)

In [120]:
# NOTE: this will change the value on the both variable
# Because initially they were both having the same value, so Python assigns a same address to both, that's why
# STRANGE
array[0] = 10
array, hex(id(array)), tensor, hex(id(tensor))

(array([10.,  2.,  3.,  4.,  5.,  6.,  7.]),
 '0x7fcd85737330',
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64),
 '0x7fcd8573b830')

In [121]:
# NOTE: this won't change the value for the both variable
# Because now Python assigned "array" variable a new address
# STRANGE
array = array + 5
array, hex(id(array)), tensor, hex(id(tensor))

(array([15.,  7.,  8.,  9., 10., 11., 12.]),
 '0x7fcd85737450',
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64),
 '0x7fcd8573b830')

In [123]:
# Tensor to NumPy
# Note: the datatype of the tensor and numpy array will be float32 (default for PyTorch)
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, tensor.dtype, numpy_tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [125]:
# NOTE: this will change the value on the both variable
# STRANGE!
tensor[0] = 15
numpy_tensor

array([15.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

### Reproducibility 

In [126]:
# trying to take random out of random

torch.rand(3,4)

tensor([[0.0610, 0.6677, 0.5372, 0.9080],
        [0.5207, 0.7174, 0.2513, 0.1789],
        [0.0340, 0.9905, 0.9938, 0.1854]])

In [127]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # NOTE: it only works for the first rand line
tensor_a = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # NOTE: have to write it again
tensor_b = torch.rand(3,4)

print(tensor_a == tensor_b)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors on GPU

In [128]:
torch.cuda.is_available()

False

In [129]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [130]:
torch.cuda.device_count()

0

In [131]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [132]:
tensor = torch.tensor([1,2,3])

print(f"Tensor device: {tensor.device}")

Tensor device: cpu


In [133]:
# move tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [134]:
# move back to CPU

tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu, tensor_back_on_cpu.device


(tensor([1, 2, 3]), device(type='cpu'))