<a href="https://colab.research.google.com/github/kvnptl/pytorch-practice/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learn PyTorch by Coding 

[1] My Github repo: https://github.com/kvnptl/pytorch-practice

[2] Reference Video: https://www.youtube.com/watch?v=Z_ikDlimN6A&t=83869s 

[3] Reference Book: https://www.learnpytorch.io/00_pytorch_fundamentals/#creating-tensors 



In [ ]:
import torch
import numpy as np
print(torch.__version__)

1.13.0+cu116


### Introduction to tensor

Document - `torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html

### Variable naming convention

- Keep scalar and vector in Lower case
- Keep MATRIX and TENSOR in Upper case

##### Scalar

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

##### Vector

In [ ]:
# vector
vector =  torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # count number of [] brackets

1

In [ ]:
vector.shape

torch.Size([2])

##### MATRIX

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0] # 0th row

tensor([7, 8])

##### TENSOR

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][1]

tensor([4, 5, 6])

In [ ]:
TENSOR[0][1][0]

tensor(4)

### RANDOM TENSORS

In [ ]:
## RANDOM TENSORS

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.5047, 0.2871, 0.0694, 0.5432],
        [0.9892, 0.6422, 0.5660, 0.2883],
        [0.6441, 0.0497, 0.8660, 0.7410]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor_2 = torch.rand(5, 3, 4)
random_tensor_2

tensor([[[0.7115, 0.5361, 0.4326, 0.5940],
         [0.5058, 0.6817, 0.0290, 0.3190],
         [0.3007, 0.7789, 0.4842, 0.9478]],

        [[0.5266, 0.0774, 0.3336, 0.3537],
         [0.7764, 0.8795, 0.3813, 0.6762],
         [0.6365, 0.1029, 0.3845, 0.2568]],

        [[0.0575, 0.8587, 0.5372, 0.6987],
         [0.6078, 0.0702, 0.9492, 0.7080],
         [0.8987, 0.9288, 0.2572, 0.7196]],

        [[0.8323, 0.6818, 0.5781, 0.1634],
         [0.7788, 0.0790, 0.9037, 0.5176],
         [0.1886, 0.8329, 0.6990, 0.7883]],

        [[0.6730, 0.0990, 0.9408, 0.6966],
         [0.2144, 0.4778, 0.8616, 0.5883],
         [0.3105, 0.4223, 0.6935, 0.3284]]])

In [ ]:
random_tensor_2.ndim

3

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224,224)) # channel, height, width
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

In [ ]:
random_tensor_3 = torch.rand(1,1,3,3)
random_tensor_3.ndim, random_tensor_3.shape

(4, torch.Size([1, 1, 3, 3]))

In [ ]:
# zeros and ones

zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))

In [ ]:
ones.dtype # default is float 32

torch.float32

### Creating a range of tensors and tesnors-like

In [ ]:
a_range = torch.arange(start=0, end=1000, step=50)
a_range.ndim, a_range.shape

(1, torch.Size([20]))

In [ ]:
# creating tensors like 
# create a new tensor same as input tensor size

alike = torch.zeros_like(input=a_range)
alike

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### TENSOR datatypes

- float32 = single precision
- float16 = half precision

In [ ]:
float_32_tensor = torch.tensor([3.,6.,9.], dtype=None, device=None, requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([1,2,3], dtype=torch.float16) # or dtype=torch.half
float_16_tensor.dtype

torch.float16

In [ ]:
tensor_mul = float_16_tensor*float_32_tensor
tensor_mul.dtype

torch.float32

### Getting information from tensors

In [ ]:
some_tensor = torch.rand(3,5, dtype=torch.float64)
some_tensor

tensor([[0.4666, 0.5376, 0.2976, 0.8701, 0.1026],
        [0.8688, 0.0773, 0.9812, 0.0906, 0.5200],
        [0.8159, 0.5572, 0.5054, 0.8782, 0.1941]], dtype=torch.float64)

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shpae of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4666, 0.5376, 0.2976, 0.8701, 0.1026],
        [0.8688, 0.0773, 0.9812, 0.0906, 0.5200],
        [0.8159, 0.5572, 0.5054, 0.8782, 0.1941]], dtype=torch.float64)
Datatype of tensor: torch.float64
Shpae of tensor: torch.Size([3, 5])
Device of tensor: cpu


### Manipulating tensors

These operations are often a wonderful dance between:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
%%time
tensor * 10

CPU times: user 987 µs, sys: 0 ns, total: 987 µs
Wall time: 1.84 ms


tensor([10, 20, 30])

In [ ]:
%%time
torch.mul(tensor, 10)

CPU times: user 54 µs, sys: 10 µs, total: 64 µs
Wall time: 67.2 µs


tensor([10, 20, 30])

In [ ]:
tensor - 5

tensor([-4, -3, -2])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 3)

tensor([4, 5, 6])

In [ ]:
# Matrix multiplication

tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
val = 0
for i in range(len(tensor)):
  val = tensor[i] * tensor[i]
print(val)

tensor(9)
CPU times: user 168 µs, sys: 30 µs, total: 198 µs
Wall time: 201 µs


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 33 µs, sys: 0 ns, total: 33 µs
Wall time: 36.2 µs


tensor(14)

In [ ]:
tensorA = torch.rand(size=(3,4))
tensorB = torch.rand(size=(4,3))
torch.matmul(tensorA, tensorB)

tensor([[0.6050, 0.8423, 0.5539],
        [0.7430, 0.8357, 0.4432],
        [0.9503, 0.6560, 0.5315]])

In [ ]:
# find min, max, sum (tensor aggregation)

x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
torch.max(x)

tensor(9)

In [ ]:
torch.sum(x)

tensor(45)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(4.5000)

### Reshaping, stacking, squeezing, and unsqueezing tensors

In [ ]:
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add extra dimention

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [ ]:
# add extra dimention

x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]), 2)

In [ ]:
# change the view

z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because they share the same memory)

z[:, 0] = 5
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# stacking

x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_vstack = torch.vstack([x,x,x])
x_vstack, x_vstack.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([3, 9]))

In [ ]:
x_hstack = torch.hstack([x_reshaped, x_reshaped, x_reshaped])
x_reshaped.shape, x_hstack, x_hstack.shape

(torch.Size([9, 1]), tensor([[5., 5., 5.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]), torch.Size([9, 3]))

In [ ]:
# squeez removes all single dimensions from the tensor

x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_squeexed = x_reshaped.squeeze()
x_squeexed, x_squeexed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# unsqueez adds a single dimension to a target tensor at a specific dimension

x_unsqueezed = x_squeexed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_unsqueezed = x_squeexed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [ ]:
# permute - rearranges the dimensions in a specific order
# REMEMBER: permute changes the same tensor in the memory location, be careful!!! 

x_original = torch.rand(size=(3, 224, 244))
print(f"x_original shape: {x_original.shape}")

x_permuted = x_original.permute(dims=(1,2,0))
print(f"x_permuted shape: {x_permuted.shape}")

x_original shape: torch.Size([3, 224, 244])
x_permuted shape: torch.Size([224, 244, 3])


In [ ]:
x_og = torch.zeros(size=(1, 2, 4))
print(f"x_og and shape: {x_og}, {x_og.shape}")
x_perm = x_og.permute(dims=(2, 1, 0))
print(f"x_perm and shape: {x_perm}, {x_perm.shape}")
x_perm[0][0][0] = 5
x_og



x_og and shape: tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]), torch.Size([1, 2, 4])
x_perm and shape: tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]), torch.Size([4, 2, 1])


tensor([[[5., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### Indexing

In [ ]:
## Indexing 

x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][0][0].item()

1

In [ ]:
x[0][2][2].item()

9

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

### PyTorch tensors and NumPy

In [ ]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array) # NOTE: NumPy default dtype is float64
array, hex(id(array)), tensor, hex(id(tensor))

(array([1., 2., 3., 4., 5., 6., 7.]),
 '0x7f1843a7a870',
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 '0x7f1843a75d60')

In [ ]:
# NOTE: this will change the value on the both variable
# Because initially they were both having the same value, so Python assigns a same address to both, that's why
# STRANGE
array[0] = 10
array, hex(id(array)), tensor, hex(id(tensor))

(array([10.,  2.,  3.,  4.,  5.,  6.,  7.]),
 '0x7f1843a7a870',
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64),
 '0x7f1843a75d60')

In [ ]:
# NOTE: this won't change the value for the both variable
# Because now Python assigned "array" variable a new address
# STRANGE
array = array + 5
array, hex(id(array)), tensor, hex(id(tensor))

(array([15.,  7.,  8.,  9., 10., 11., 12.]),
 '0x7f1843ac37b0',
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64),
 '0x7f1843a75d60')

In [ ]:
# Tensor to NumPy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor[0] = 15
numpy_tensor

array([15.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

### Reproducibility 

In [ ]:
# trying to take random out of random

torch.rand(3,4)

tensor([[0.9487, 0.9163, 0.9569, 0.1420],
        [0.1723, 0.0360, 0.9920, 0.4465],
        [0.0298, 0.9303, 0.3544, 0.6962]])

In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # it only works for the first rand line
tensor_a = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # have to write it again
tensor_b = torch.rand(3,4)

print(tensor_a == tensor_b)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
!nvidia-smi

Tue Jan  3 00:29:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
tensor = torch.tensor([1,2,3])

print(f"Tensor device: {tensor.device}")

Tensor device: cpu


In [ ]:
# move tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# move back to CPU

tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu, tensor_back_on_cpu.device


(tensor([1, 2, 3]), device(type='cpu'))