<a href="https://colab.research.google.com/github/kvnptl/pytorch-practice/blob/main/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor_rand = torch.rand(size=(7,7))
tensor_rand


tensor([[0.7895, 0.8679, 0.0424, 0.1036, 0.1430, 0.4077, 0.6093],
        [0.9338, 0.2554, 0.2248, 0.7529, 0.2267, 0.5512, 0.9983],
        [0.5047, 0.0621, 0.6551, 0.8111, 0.1191, 0.4001, 0.2929],
        [0.0107, 0.6423, 0.9060, 0.5174, 0.5718, 0.3735, 0.0715],
        [0.2925, 0.8756, 0.1828, 0.5862, 0.0862, 0.6533, 0.0704],
        [0.3325, 0.4441, 0.7893, 0.3834, 0.7204, 0.3234, 0.7096],
        [0.5890, 0.1811, 0.5391, 0.7742, 0.2621, 0.8681, 0.2557]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
tensor_rand_2 = torch.rand(size=(1,7))
# Perform matrix multiplication 
torch.matmul(tensor_rand, tensor_rand_2.T)

tensor([[1.2906],
        [1.6543],
        [1.0220],
        [1.6439],
        [0.8978],
        [2.2021],
        [1.1440]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_a = torch.rand(7,7)
tensor_b = torch.rand(1,7)


# Matrix multiply tensors
torch.matmul(tensor_a, tensor_b.T)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
# Same for both CUDA and CPU as mentioned on pytorch documentation


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor_1 = torch.rand(2,3).to(device)
tensor_2 = torch.rand(2,3).to(device)
tensor_1, tensor_2


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [10]:
# Perform matmul on tensor_A and tensor_B
tensor_mul = torch.matmul(tensor_1, tensor_2.T)

### 8. Find the maximum and minimum values of the output of 7.

In [11]:
# Find max

# Find min
torch.max(tensor_mul), torch.min(tensor_mul)

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [12]:
# Find arg max
# Find arg min
torch.argmax(tensor_mul), torch.argmin(tensor_mul)

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [13]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)


# Create random tensor
tensor_random = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_new = tensor_random.squeeze()


# Print out tensors and their shapes
print(f"First tensor: {tensor_random}, {tensor_random.shape}")
print(f"Second tensor: {tensor_new}, {tensor_new.shape}")


First tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10])
Second tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10])
